export const categories: string[] = [
  "Addiction Treatment",
  "Anxiety",
  "Cancer",
  "PCDS",
  "Skin",
  "SkinCare",
  "Sleep",
  "Allergies",
  "Anti Ageing",
  "Arthritis",
  "Asthma",
  "Back Pain",
  "Blood Pressure",
  "Bronchitis",
  "Cardiovascular",
  "Cholesterol",
  "Cold and Flu",
  "Constipation",
  "Cough",
  "Diabetes",
  "Diarrhea",
  "Digestive Health",
  "Ear Infections",
  "Eczema",
  "Epilepsy",
  "Eye Care",
  "Fever",
  "Fibromyalgia",
  "Gastroesophageal Reflux Disease (GERD)",
  "Gout",
  "Hair Loss",
  "Hay Fever",
  "Heart Disease",
  "Hemorrhoids",
  "Hepatitis",
  "Herpes",
  "HIV/AIDS",
  "Hypertension",
  "Hypothyroidism",
  "IBS (Irritable Bowel Syndrome)",
  "Immune System",
  "Infections",
  "Influenza",
  "Insomnia",
  "Irritable Skin",
  "Kidney Disease",
  "Liver Disease",
  "Lung Disease",
  "Men's Health",
  "Mental Health",
  "Migraines",
  "Multiple Sclerosis",
  "Muscle Pain",
  "Nausea",
  "Neuropathy",
  "Obesity",
  "Osteoporosis",
  "Pain Relief",
  "Parkinson's Disease",
  "Psoriasis",
  "Rheumatism",
  "Seizures",
  "Sinusitis",
  "STD Treatment",
  "Stomach Ache",
  "Stroke",
  "Thyroid Disorders",
  "Tonsillitis",
  "Tuberculosis",
  "Ulcers",
  "Urinary Tract Infections",
  "Varicose Veins",
  "Vitamins and Supplements",
  "Women's Health",
];
