export const categories: string[] = [
  "Addiction Treatment",
  "Anxiety",
  "Cancer",
  "PCDS",
  "Skin",
  "SkinCare",
  "Sleep",
  "Allergies",
  "Anti Ageing",
  "Arthritis",
  "Asthma",
  "Back Pain",
  "Blood Pressure",
  "Bronchitis",
  "Cardiovascular",
  "Cholesterol",
  "Cold and Flu",
  "Constipation",
  "Cough",
  "Diabetes",
  "Diarrhea",
  "Digestive Health",
  "Ear Infections",
  "Eczema",
  "Epilepsy",
  "Eye Care",
  "Fever",
  "Fibromyalgia",
  "Gastroesophageal Reflux Disease (GERD)",
  "Gout",
  "Hair Loss",
  "Hay Fever",
  "Heart Disease",
  "Hemorrhoids",
  "Hepatitis",
  "Herpes",
  "HIV/AIDS",
  "Hypertension",
  "Hypothyroidism",
  "IBS (Irritable Bowel Syndrome)",
  "Immune System",
  "Infections",
  "Influenza",
  "Insomnia",
  "Irritable Skin",
  "Kidney Disease",
  "Liver Disease",
  "Lung Disease",
  "Men's Health",
  "Mental Health",
  "Migraines",
  "Multiple Sclerosis",
  "Muscle Pain",
  "Nausea",
  "Neuropathy",
  "Obesity",
  "Osteoporosis",
  "Pain Relief",
  "Parkinson's Disease",
  "Psoriasis",
  "Rheumatism",
  "Seizures",
  "Sinusitis",
  "STD Treatment",
  "Stomach Ache",
  "Stroke",
  "Thyroid Disorders",
  "Tonsillitis",
  "Tuberculosis",
  "Ulcers",
  "Urinary Tract Infections",
  "Varicose Veins",
  "Vitamins and Supplements",
  "Women's Health",
];
export const AllCatagories: Category[] = [
  {
    main_catagory: "Addiction Treatment",
    slug: "addiction-treatment",
    sub_catagories: [
      "Alcohol Dependence",
      "Drug Addiction",
      "Gambling Addiction",
    ],
  },
  {
    main_catagory: "Anxiety",
    slug: "anxiety",
    sub_catagories: [
      "Generalized Anxiety Disorder",
      "Panic Disorder",
      "Social Anxiety Disorder",
    ],
  },
  {
    main_catagory: "Cancer",
    slug: "cancer",
    sub_catagories: ["Breast Cancer", "Lung Cancer", "Prostate Cancer"],
  },
  {
    main_catagory: "PCDS",
    slug: "pcds",
    sub_catagories: ["PCD Type 1", "PCD Type 2"],
  },
  {
    main_catagory: "Skin",
    slug: "skin",
    sub_catagories: ["Acne", "Dermatitis", "Psoriasis"],
  },
  {
    main_catagory: "SkinCare",
    slug: "skincare",
    sub_catagories: ["Moisturizers", "Sunscreens", "Anti-Aging Products"],
  },
  {
    main_catagory: "Sleep",
    slug: "sleep",
    sub_catagories: ["Insomnia", "Sleep Apnea", "Narcolepsy"],
  },
  {
    main_catagory: "Allergies",
    slug: "allergies",
    sub_catagories: ["Hay Fever", "Food Allergies", "Drug Allergies"],
  },
  {
    main_catagory: "Anti Ageing",
    slug: "anti-ageing",
    sub_catagories: ["Wrinkles", "Age Spots", "Skin Firmness"],
  },
  {
    main_catagory: "Arthritis",
    slug: "arthritis",
    sub_catagories: ["Osteoarthritis", "Rheumatoid Arthritis", "Gout"],
  },
  {
    main_catagory: "Asthma",
    slug: "asthma",
    sub_catagories: ["Allergic Asthma", "Exercise-Induced Asthma"],
  },
  {
    main_catagory: "Back Pain",
    slug: "back-pain",
    sub_catagories: ["Lower Back Pain", "Sciatica", "Spinal Stenosis"],
  },
  {
    main_catagory: "Blood Pressure",
    slug: "blood-pressure",
    sub_catagories: ["Hypertension", "Hypotension"],
  },
  {
    main_catagory: "Bronchitis",
    slug: "bronchitis",
    sub_catagories: ["Acute Bronchitis", "Chronic Bronchitis"],
  },
  {
    main_catagory: "Cardiovascular",
    slug: "cardiovascular",
    sub_catagories: ["Heart Disease", "Arrhythmia", "Heart Failure"],
  },
  {
    main_catagory: "Cholesterol",
    slug: "cholesterol",
    sub_catagories: ["Hypercholesterolemia", "Hyperlipidemia"],
  },
  {
    main_catagory: "Cold and Flu",
    slug: "cold-and-flu",
    sub_catagories: ["Common Cold", "Influenza"],
  },
  {
    main_catagory: "Constipation",
    slug: "constipation",
    sub_catagories: [
      "Chronic Idiopathic Constipation",
      "Functional Constipation",
    ],
  },
  {
    main_catagory: "Cough",
    slug: "cough",
    sub_catagories: ["Dry Cough", "Productive Cough"],
  },
  {
    main_catagory: "Diabetes",
    slug: "diabetes",
    sub_catagories: ["Type 1 Diabetes", "Type 2 Diabetes"],
  },
  {
    main_catagory: "Diarrhea",
    slug: "diarrhea",
    sub_catagories: ["Acute Diarrhea", "Chronic Diarrhea"],
  },
  {
    main_catagory: "Digestive Health",
    slug: "digestive-health",
    sub_catagories: [
      "Irritable Bowel Syndrome",
      "Gastroesophageal Reflux Disease",
    ],
  },
  {
    main_catagory: "Ear Infections",
    slug: "ear-infections",
    sub_catagories: ["Otitis Media", "Swimmer's Ear"],
  },
  {
    main_catagory: "Eczema",
    slug: "eczema",
    sub_catagories: ["Atopic Dermatitis", "Contact Dermatitis"],
  },
  {
    main_catagory: "Epilepsy",
    slug: "epilepsy",
    sub_catagories: ["Focal Seizures", "Generalized Seizures"],
  },
  {
    main_catagory: "Eye Care",
    slug: "eye-care",
    sub_catagories: ["Cataracts", "Glaucoma"],
  },
  {
    main_catagory: "Fever",
    slug: "fever",
    sub_catagories: ["Viral Fever", "Bacterial Fever"],
  },
  {
    main_catagory: "Fibromyalgia",
    slug: "fibromyalgia",
    sub_catagories: ["Primary Fibromyalgia", "Secondary Fibromyalgia"],
  },
  {
    main_catagory: "Gastroesophageal Reflux Disease (GERD)",
    slug: "gerd",
    sub_catagories: ["Non-Erosive Reflux Disease", "Erosive Reflux Disease"],
  },
  {
    main_catagory: "Gout",
    slug: "gout",
    sub_catagories: ["Acute Gout", "Chronic Gout"],
  },
  {
    main_catagory: "Hair Loss",
    slug: "hair-loss",
    sub_catagories: ["Androgenic Alopecia", "Alopecia Areata"],
  },
  {
    main_catagory: "Hay Fever",
    slug: "hay-fever",
    sub_catagories: [
      "Seasonal Allergic Rhinitis",
      "Perennial Allergic Rhinitis",
    ],
  },
  {
    main_catagory: "Heart Disease",
    slug: "heart-disease",
    sub_catagories: ["Coronary Artery Disease", "Heart Attack"],
  },
  {
    main_catagory: "Hemorrhoids",
    slug: "hemorrhoids",
    sub_catagories: ["Internal Hemorrhoids", "External Hemorrhoids"],
  },
  {
    main_catagory: "Hepatitis",
    slug: "hepatitis",
    sub_catagories: ["Hepatitis A", "Hepatitis B", "Hepatitis C"],
  },
  {
    main_catagory: "Herpes",
    slug: "herpes",
    sub_catagories: ["Oral Herpes", "Genital Herpes"],
  },
  {
    main_catagory: "HIV/AIDS",
    slug: "hiv-aids",
    sub_catagories: ["HIV Infection", "AIDS"],
  },
  {
    main_catagory: "Hypertension",
    slug: "hypertension",
    sub_catagories: ["Essential Hypertension", "Secondary Hypertension"],
  },
  {
    main_catagory: "Hypothyroidism",
    slug: "hypothyroidism",
    sub_catagories: ["Primary Hypothyroidism", "Secondary Hypothyroidism"],
  },
  {
    main_catagory: "IBS (Irritable Bowel Syndrome)",
    slug: "ibs",
    sub_catagories: ["IBS-D (Diarrhea)", "IBS-C (Constipation)"],
  },
  {
    main_catagory: "Immune System",
    slug: "immune-system",
    sub_catagories: ["Autoimmune Diseases", "Immunodeficiency"],
  },
  {
    main_catagory: "Infections",
    slug: "infections",
    sub_catagories: ["Bacterial Infections", "Viral Infections"],
  },
  {
    main_catagory: "Influenza",
    slug: "influenza",
    sub_catagories: ["Seasonal Flu", "Pandemic Flu"],
  },
  {
    main_catagory: "Insomnia",
    slug: "insomnia",
    sub_catagories: ["Acute Insomnia", "Chronic Insomnia"],
  },
  {
    main_catagory: "Irritable Skin",
    slug: "irritable-skin",
    sub_catagories: ["Contact Dermatitis", "Atopic Dermatitis"],
  },
  {
    main_catagory: "Kidney Disease",
    slug: "kidney-disease",
    sub_catagories: ["Chronic Kidney Disease", "Acute Kidney Injury"],
  },
  {
    main_catagory: "Liver Disease",
    slug: "liver-disease",
    sub_catagories: ["Cirrhosis", "Hepatitis"],
  },
  {
    main_catagory: "Lung Disease",
    slug: "lung-disease",
    sub_catagories: ["Chronic Obstructive Pulmonary Disease (COPD)", "Asthma"],
  },
  {
    main_catagory: "Men's Health",
    slug: "mens-health",
    sub_catagories: ["Prostate Health", "Erectile Dysfunction"],
  },
  {
    main_catagory: "Mental Health",
    slug: "mental-health",
    sub_catagories: ["Depression", "Bipolar Disorder"],
  },
  {
    main_catagory: "Migraines",
    slug: "migraines",
    sub_catagories: ["Migraine with Aura", "Migraine without Aura"],
  },
  {
    main_catagory: "Multiple Sclerosis",
    slug: "multiple-sclerosis",
    sub_catagories: ["Relapsing-Remitting MS", "Progressive MS"],
  },
  {
    main_catagory: "Muscle Pain",
    slug: "muscle-pain",
    sub_catagories: ["Myalgia", "Muscle Strain"],
  },
  {
    main_catagory: "Nausea",
    slug: "nausea",
    sub_catagories: ["Motion Sickness", "Morning Sickness"],
  },
  {
    main_catagory: "Neuropathy",
    slug: "neuropathy",
    sub_catagories: ["Peripheral Neuropathy", "Autonomic Neuropathy"],
  },
  {
    main_catagory: "Obesity",
    slug: "obesity",
    sub_catagories: ["Morbid Obesity", "Childhood Obesity"],
  },
  {
    main_catagory: "Osteoporosis",
    slug: "osteoporosis",
    sub_catagories: ["Primary Osteoporosis", "Secondary Osteoporosis"],
  },
  {
    main_catagory: "Pain Relief",
    slug: "pain-relief",
    sub_catagories: ["Chronic Pain", "Acute Pain"],
  },
  {
    main_catagory: "Parkinson's Disease",
    slug: "parkinsons-disease",
    sub_catagories: ["Early-Onset Parkinson's", "Late-Onset Parkinson's"],
  },
  {
    main_catagory: "Psoriasis",
    slug: "psoriasis",
    sub_catagories: ["Plaque Psoriasis", "Guttate Psoriasis"],
  },
  {
    main_catagory: "Rheumatism",
    slug: "rheumatism",
    sub_catagories: ["Rheumatoid Arthritis", "Ankylosing Spondylitis"],
  },
  {
    main_catagory: "Seizures",
    slug: "seizures",
    sub_catagories: ["Focal Seizures", "Generalized Seizures"],
  },
  {
    main_catagory: "Sinusitis",
    slug: "sinusitis",
    sub_catagories: ["Acute Sinusitis", "Chronic Sinusitis"],
  },
  {
    main_catagory: "STD Treatment",
    slug: "std-treatment",
    sub_catagories: ["Chlamydia", "Gonorrhea"],
  },
  {
    main_catagory: "Stomach Ache",
    slug: "stomach-ache",
    sub_catagories: ["Gastritis", "Peptic Ulcer"],
  },
  {
    main_catagory: "Stroke",
    slug: "stroke",
    sub_catagories: ["Ischemic Stroke", "Hemorrhagic Stroke"],
  },
  {
    main_catagory: "Thyroid Disorders",
    slug: "thyroid-disorders",
    sub_catagories: ["Hypothyroidism", "Hyperthyroidism"],
  },
  {
    main_catagory: "Tonsillitis",
    slug: "tonsillitis",
    sub_catagories: ["Acute Tonsillitis", "Chronic Tonsillitis"],
  },
  {
    main_catagory: "Tuberculosis",
    slug: "tuberculosis",
    sub_catagories: ["Latent TB", "Active TB"],
  },
  {
    main_catagory: "Ulcers",
    slug: "ulcers",
    sub_catagories: ["Peptic Ulcers", "Mouth Ulcers"],
  },
  {
    main_catagory: "Urinary Tract Infections",
    slug: "urinary-tract-infections",
    sub_catagories: ["Cystitis", "Urethritis"],
  },
  {
    main_catagory: "Varicose Veins",
    slug: "varicose-veins",
    sub_catagories: ["Superficial Varicose Veins", "Deep Varicose Veins"],
  },
  {
    main_catagory: "Vitamins and Supplements",
    slug: "vitamins-and-supplements",
    sub_catagories: ["Multivitamins", "Herbal Supplements"],
  },
  {
    main_catagory: "Women's Health",
    slug: "womens-health",
    sub_catagories: ["Menstrual Disorders", "Menopause"],
  },
];
