import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/gernal/header/header";
import { Toaster } from "@/components/ui/sonner";
import Searchbar from "@/components/gernal/header/searchbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-black">
      <body className={inter.className}>
        <>
          <Header />
          {children}
          <div className="py-6 bg-white z-50 border-t sticky bottom-0 lg:hidden">
            <Searchbar mobile className="mx-auto" />
          </div>
        </>
        <Toaster richColors />
      </body>
    </html>
  );
}
